from pathlib import Path
p=Path(r'C:\Users\natan\Documents\Codex\2026-06-05\https-pricing-calculator2-beta-vercel-app\outputs\site\assets\index-ml-atualizado.js')
js=p.read_text(encoding='utf-8')
start=js.index('T=p=>{var M;')
end=js.index('},I=p=>{', start)
new='''T=async p=>{var M;if(!p||!p.trim()){d({type:"error",message:"Cole um link válido"});return}const P=kp(p);if(!P){d({type:"error",message:"Link inválido ou não suportado"});return}if(!P.detected){d({type:"warning",message:"Marketplace não identificado. Selecione manualmente."}),m(le=>({...le,marketplace:"manual"}));return}const mapCat=le=>{const ye=(le||"").toLowerCase();return ye.includes("roup")||ye.includes("moda")||ye.includes("calçado")||ye.includes("acess")?"Vestuário e Acessórios":ye.includes("casa")||ye.includes("decora")||ye.includes("móveis")?"Casa e Decoração":ye.includes("beleza")||ye.includes("cuidado")||ye.includes("perfum")?"Beleza e Cuidado Pessoal":ye.includes("esporte")||ye.includes("fitness")?"Esportes e Fitness":ye.includes("brinquedo")||ye.includes("jogo")?"Brinquedos e Jogos":ye.includes("alimento")||ye.includes("bebida")?"Alimentos e Bebidas":ye.includes("auto")||ye.includes("veículo")?"Automotivo":ye.includes("ferrament")?"Ferramentas":ye.includes("papelaria")||ye.includes("escritório")?"Papelaria e Escritório":ye.includes("pet")?"Pet Shop":ye.includes("saúde")?"Saúde":ye.includes("eletr")||ye.includes("informática")||ye.includes("celular")?"Eletrônicos":"Outros"};m(le=>({...le,marketplace:P.marketplace})),P.sellingPrice&&m(le=>({...le,sellingPrice:P.sellingPrice}));if(P.marketplace==="mercadolivre_classico"&&P.productId){const le=P.productId.toUpperCase().startsWith("MLB")?P.productId.toUpperCase():`MLB${P.productId}`;d({type:"warning",message:"Buscando dados do anúncio no Mercado Livre..."});try{const ye=await fetch(`https://api.mercadolibre.com/items/${le}`);if(!ye.ok)throw new Error("Item não encontrado");const Wt=await ye.json();let Ve="Outros";if(Wt.category_id)try{const _t=await fetch(`https://api.mercadolibre.com/categories/${Wt.category_id}`);if(_t.ok){const jt=await _t.json();Ve=mapCat(jt.name)}}catch{}m(_t=>({..._t,marketplace:P.marketplace,sku:le,name:Wt.title||_t.name,sellingPrice:Wt.price!=null?String(Wt.price):_t.sellingPrice,category:Ve,originalUrl:Wt.permalink||p})),d({type:"success",message:"Dados do anúncio Mercado Livre preenchidos automaticamente."})}catch(ye){console.error("Erro ao buscar anúncio Mercado Livre:",ye),d({type:"warning",message:"Mercado Livre detectado, mas não foi possível buscar os dados do anúncio."})}setTimeout(()=>d({type:null,message:""}),4e3);return}d({type:"success",message:`${((M=Je[P.marketplace])==null?void 0:M.name)||"Marketplace"} detectado! Marketplace pré-selecionado.`}),setTimeout(()=>d({type:null,message:""}),3e3)}'''
js=js[:start]+new+js[end:]
p.write_text(js,encoding='utf-8')
print('updated Mercado Livre link autofill')
